import {
	Box,
	Button,
	Flex,
	FormLabel,
	Input,
	Textarea,
	VStack,
} from "@chakra-ui/react";
import styles from "./page.module.css";
import CodeView from "@/components/CodeView";

export default function Home() {
	const code = `import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`;

	code.split("\n").forEach((a) => console.log(a));

	return (
		<main className={styles.main}>
			<Box
				display="grid"
				gridTemplateColumns="50% 50%"
				w="100%"
				minH="100vh"
			>
				<CodeView code={code}></CodeView>
				<Flex
					bgColor="grey"
					justifyContent="center"
					alignContent="center"
				>
					<VStack justifyContent={"center"} w="100%" px="4rem">
						<FormLabel alignSelf={"flex-start"}>
							General feedback
						</FormLabel>
						<Textarea bgColor="white" h={300}></Textarea>
						<Button>Submit Review</Button>
					</VStack>
				</Flex>
			</Box>
			<div style={{ display: "flex", flexDirection: "column" }}></div>
		</main>
	);
}
