import styles from "./page.module.css";
import CodeView from "@/components/CodeView";

export default function Home() {
	const code = `import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`;

	code.split("\n").forEach((a) => console.log(a));

	return (
		<main className={styles.main}>
			<div style={{ display: "flex", flexDirection: "column" }}>
				<CodeView code={code}></CodeView>
			</div>
		</main>
	);
}
