"use client";
import {
	Box,
	Button,
	Flex,
	FormLabel,
	Textarea,
	VStack,
} from "@chakra-ui/react";
import CodeView from "@/components/CodeView";
import { useCommentStore } from "@/store/CommentStore";
import { useState } from "react";
import { CreateCommentBody } from "@/app/api/github/[installationId]/repos/[owner]/[repo]/pulls/[pull_number]/comments/route";

export default function Home() {
	const { comments, clear: clearStore } = useCommentStore();
	const code = `import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`;

	const [feedback, setFeedback] = useState("");

	const onSubmit = async () => {
		console.log("skal prøve å persistere data");

		const body: CreateCommentBody = {
			comments: comments,
			commit_id: "cb50c0436d55aec507b7db213af64fd66cf3b27f",
			feedback: feedback,
		};

		await fetch(
			"/api/github/repos/Testing-PCR/demo-repository/pulls/1/comments",
			{
				method: "POST",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify(body),
				cache: "no-store",
			}
		).then((res) => {
			if (res.ok) {
				clearStore();
				setFeedback("");
				//TODO: redirect til ny side
			}
		});
	};

	return (
		<Box display="grid" gridTemplateColumns="50% 50%" w="100%" minH="100vh">
			<CodeView code={code} />
			<Flex
				bgColor="rgb(243, 164, 74)"
				justifyContent="center"
				alignContent="center"
			>
				<VStack justifyContent={"center"} w="100%" px="4rem">
					<FormLabel alignSelf={"flex-start"}>
						General feedback
					</FormLabel>
					<Textarea
						bgColor="white"
						h={300}
						onChange={(e) => setFeedback(e.target.value)}
					></Textarea>
					<Button onClick={onSubmit}>Submit Review</Button>
				</VStack>
			</Flex>
		</Box>
	);
}
