"use client";
import { Box, Flex, FormLabel, VStack, Text, Button } from "@chakra-ui/react";
import CommentViewer from "@/components/CommentViewer";
import { useState, useEffect } from "react";

interface ViewFeedbackPageProps {
	params: {
		submissionId: number;
	};
}

const ViewFeedbackPage: React.FC<ViewFeedbackPageProps> = ({
	params: { submissionId },
}) => {
	//TODO fetcch submission
	const code = `import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}`;
	const [data, setData] = useState<any[]>([]);
	const [reviewId, setReviewId] = useState(0);
	useEffect(() => {
		const fetchData = async () =>
			await fetch("http://0.0.0.0:8090/review/" + submissionId, {
				cache: "no-store",
			})
				.then((res) => res.json())
				.then((res) => setData(res));

		fetchData();
	}, []);

	var mid: { lineNumber: number; text: string }[] = [];

	data[reviewId]?.comments.forEach((el: any) => mid.push(el));

	return (
		<Box display="grid" gridTemplateColumns="50% 50%" w="100%" minH="100vh">
			<CommentViewer code={code} comments={mid} />
			<Flex
				bgColor="rgb(243, 164, 74)"
				justifyContent="center"
				alignContent="center"
			>
				<VStack justifyContent={"center"} w="100%" px="4rem">
					<FormLabel alignSelf={"flex-start"}>
						General feedback
					</FormLabel>
					{/* <Textarea bgColor="white" h={300}></Textarea> */}
					<Text
						textAlign="left"
						bgColor="white"
						h="300"
						w="100%"
						p="0.5rem 1rem"
					>
						Koden er helt ok
					</Text>
					{/* <Button>Submit Review</Button> */}
				</VStack>

				<Button onClick={() => setReviewId((id) => id + 1)}>
					Next Review
				</Button>
			</Flex>
		</Box>
	);
};

export default ViewFeedbackPage;
